backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: tours
    label: Wycieczki
    folder: tours
    create: true
    identifier_field: name
    fields:
      - { label: "Nazwa", name: "title", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "datetime" }
      - { label: "Kontynent", name: "continent", widget: "string" }
      - { label: "Państwo", name: "country", widget: "string" }
      - { label: "Miasto", name: "city", widget: "string" }
      - { label: "Wylot (miejsce)", name: "departure", widget: "string" }
      - { label: "Przylot (miejsce)", name: "arrival", widget: "string" }
      - {
          label: "0cena",
          name: "rating",
          widget: "number",
          min: 0,
          max: 10,
          valueType: "float",
        }
      - { label: "Hotel", name: "hotel", widget: "string" }
      - { label: "Obraz", name: "thumbnail", widget: "image" }
      - { label: "Cena", name: "price", widget: "number" }
      - { label: "Promocja", name: "promotion", widget: "boolean" }
      - { label: "Treść", name: "body", widget: "markdown" }
